### ISSUE TITLE
Does not work in Firefox >= 57 / with some sample images

### ISSUE THREAD

**Issue by Smile4ever** [gcp/wxif#8] opened 2017-12-15 19:27 UTC
Partial duplicate of/related to #1 #5 #6 and also #3

Does not work at all for
* https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Canon_EOS_300D_%281%29.jpg/1200px-Canon_EOS_300D_%281%29.jpg
* https://shop.usa.canon.com/wcsstore/ExtendedSitesCatalogAssetStore/eos-t7i-18-55_1_xl.jpg
* https://upload.wikimedia.org/wikipedia/commons/b/bb/Beautifu_nature.jpg

Works half for https://upload.wikimedia.org/wikipedia/commons/2/2e/Frost_fog.jpg

Unknown localization message                                  stringBundle.js:11
Unknown localization message make  stringBundle.js:11
Unknown localization message sony  stringBundle.js:11
Unknown localization message model  stringBundle.js:11
Unknown localization message dsc-rx100  stringBundle.js:11
Unknown localization message orientation  stringBundle.js:11
Unknown localization message normal  stringBundle.js:11
Unknown localization message adobe photoshop elements 7.0 windows  stringBundle.js:11
Unknown localization message 0.050s (1/20)  stringBundle.js:11
Unknown localization message ƒ/11.0  stringBundle.js:11
Unknown localization message aperture priority (semi-auto)  stringBundle.js:11
Unknown localization message 125  stringBundle.js:11
Unknown localization message +0.30ev  stringBundle.js:11
Unknown localization message no (enforced)  stringBundle.js:11
Unknown localization message   stringBundle.js:11
Unknown localization message srgb  stringBundle.js:11
Unknown localization message 18.4mm 50mm=35mm equivalent  stringBundle.js:11
Unknown localization message date  stringBundle.js:11
Unknown localization message 2016-12-15 10:35:15 (no tz)  stringBundle.js:11
Unknown localization message lens  stringBundle.js:11
Unknown localization message 10.4-37.1mm ƒ/1.8-4.9  stringBundle.js:11
Unknown localization message error  stringBundle.js:11
Unknown localization message xmp,xmperror while interpreting %s data. %s meta data shown might be not complete. please report this problem with an example image. typeerror: parser.parsefrombuffer is not a function
TypeError: cannot use 'in' operator to search for 'canGoBack' in 'browser'[Learn More]  tabbrowser.xml:2485:1
TypeError: browser.messageManager is undefined[Learn More]  webext-panels.js:62:5

Works half for https://upload.wikimedia.org/wikipedia/commons/7/76/Angry_lion.jpg

Unknown localization message nikon corporation  stringBundle.js:11
Unknown localization message nikon d5200  stringBundle.js:11
Unknown localization message adobe photoshop cc 2015 (windows)  stringBundle.js:11
Unknown localization message 0.0063s (1/160)  stringBundle.js:11
Unknown localization message 100  stringBundle.js:11
Unknown localization message +1.67ev  stringBundle.js:11
Unknown localization message ƒ/1.0  stringBundle.js:11
Unknown localization message focalplanexres  stringBundle.js:11
Unknown localization message focalplaneunits  stringBundle.js:11
Unknown localization message lensmodel  stringBundle.js:11
Unknown localization message 0.0 mm f/0.0  stringBundle.js:11
Unknown localization message 2017-05-23 16:10:31 (no tz)  stringBundle.js:11
TypeError: cannot use 'in' operator to search for 'canGoBack' in 'browser'[Learn More]  tabbrowser.xml:2485:1
TypeError: browser.messageManager is undefined[Learn More]  webext-panels.js:62:5

Works half = I get some errors about localization messages. In the other cases ("not at all") I don't even get those error messages.

**Comment by Eagle3386** [comment] 2018-01-14 11:12
Regarding the first linked image, I just wanted to clarify that the image's EXIF data ist completely missing.

Both, the [Exif Viewer](https://addons.mozilla.org/en-US/firefox/addon/exif-viewer/) by Alan Raskin and Windows' file properties dialog confirm this.

**Comment by Eagle3386** [comment] 2018-01-23 14:15
@gcp, since
- I confirmed that the reported image is already missing EXIF data,
- even provided instructions for anybody to confirm this on her/his own and
- can't reproduce the errors mentioned by @Smile4ever's for her/his [last linked image](https://upload.wikimedia.org/wikipedia/commons/7/76/Angry_lion.jpg),
I'd like to suggest to close this issue as "not reproducible".

**Comment by gcp** [comment] 2018-01-23 14:21
I actually see:
User Comment | File source: http://commons.wikimedia.org/wiki/File:Canon_EOS_300D_(1).jpg
in the first one.

The others work. Maybe a dupe of #3?

**Closed by gcp** 2018-01-23 14:21 UTC
